language: node_js

node_js:
  - 10

stages:
  - continousIntegration
  - continousDelivery
  - systemtests

addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN

jobs:
  include:
    - stage: continousIntegration
      before_install:
        - chmod +x gradlew
      script: ./gradlew sonarqube
    - stage: continousDelivery
      script:
        - heroku container:login
        - heroku container:push web -a $HEROKU_STAGING_APP
        - heroku container:release web -a $HEROKU_STAGING_APP
    - stage: systemtests
      before_install:
        - sudo apt-get update
      install:
        - sudo apt install curl
        - npm install -g newman
      script:
        - while [ $(curl -o /dev/null -s -w "%{http_code}\n" https://$HEROKU_STAGING_APP.herokuapp.com/) != 404 ];do echo 'Waiting for the Application to be started'; sleep 5; done
        - newman run src/test/java/systemtests/collection/CRUD.postman_collection.json -e src/test/java/systemtests/environment/justicenode.postman_environment.json
